Fix S3 backups

diff --git a/bin/v-backup-user b/bin/v-backup-user
--- a/bin/v-backup-user
+++ b/bin/v-backup-user
@@ -905,7 +905,7 @@ s3_backup() {
     
     # Debug info
     echo -e "$(date "+%F %T") Remote: s3://$BUCKET${BPATH}$user.$date.tar"
-    options=(--region="$HOST" --access_key="$USERNAME" --secret_key="$PASSWORD")
+    options=(--access_key="$USERNAME" --secret_key="$PASSWORD" --host="$HOST" --host-bucket="$BUCKET" --no-check-certificate)
     
     
     # Checking retention
@@ -925,16 +925,22 @@ s3_backup() {
     echo -e "$(date "+%F %T") Uploading $user.$date.tar ..."
     if [ "$localbackup" = 'yes' ]; then
         cd $BACKUP
-        s3cmd ${options[@]} put $user.$date.tar s3://$BUCKET${BPATH}/$user.$date.tar > /dev/null 2>&1
+        s3cmd ${options[@]} put $user.$backup_new_date.tar s3://$BUCKET${BPATH}/$user.$backup_new_date.tar > /dev/null 2>&1
+        rc=$?
+        if [ "$rc" -ne 0 ]; then
+            echo "$(date "+%F %T") s3cmd failed to upload $user.$backup_new_date.tar" |tee -a $BACKUP/$user.log
+            #check_result "$E_CONNECT" "s3cmd failed to upload $user.$backup_new_date.tar"
+        fi
     else
         cd $tmpdir
         tar -cf $BACKUP/$user.$date.tar .
         cd $BACKUP/
-        s3cmd ${options[@]} put $user.$date.tar s3://$BUCKET${BPATH}$user.$date.tar > /dev/null 2>&1
+        s3cmd ${options[@]} put $user.$backup_new_date.tar s3://$BUCKET${BPATH}$user.$backup_new_date.tar > /dev/null 2>&1
         rc=$?
         #rm -f $user.$date.tar
         if [ "$rc" -ne 0 ]; then
-            check_result "$E_CONNECT" "s3cmd failed to upload $user.$date.tar"
+            echo "$(date "+%F %T") s3cmd failed to upload $user.$backup_new_date.tar" |tee -a $BACKUP/$user.log
+            check_result "$E_CONNECT" "s3cmd failed to upload $user.$backup_new_date.tar"
         fi
     fi
 }
